spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
#      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-server

  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
server:
  port: 8881
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/